name: map_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  yandex_mapkit_lite: ^2.0.2
  geolocator: ^11.0.0
  yandex_geocoder: ^2.3.1
  cupertino_icons: ^1.0.6
  rive: ^0.13.2
  easy_debounce: ^2.0.3
  dartz: ^0.10.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/rive/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
